//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalkingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogWalkingApp.Resources.FormTitles", typeof(FormTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog Editor.
        /// </summary>
        public static string DogEditor {
            get {
                return ResourceManager.GetString("DogEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐕 Dog Editor.
        /// </summary>
        public static string DogEditorWithIcon {
            get {
                return ResourceManager.GetString("DogEditorWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Edit Dog.
        /// </summary>
        public static string EditDog {
            get {
                return ResourceManager.GetString("EditDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Edit Walk.
        /// </summary>
        public static string EditWalk {
            get {
                return ResourceManager.GetString("EditWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Dog Walking Manager.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔐 Login.
        /// </summary>
        public static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐕 Dog Walking Manager.
        /// </summary>
        public static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog Walking Manager - Hierarchical View.
        /// </summary>
        public static string MainFormHierarchical {
            get {
                return ResourceManager.GetString("MainFormHierarchical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐕 Add New Dog.
        /// </summary>
        public static string NewDog {
            get {
                return ResourceManager.GetString("NewDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚶 Add New Walk.
        /// </summary>
        public static string NewWalk {
            get {
                return ResourceManager.GetString("NewWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Validation Error.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk Editor.
        /// </summary>
        public static string WalkEditor {
            get {
                return ResourceManager.GetString("WalkEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚶 Walk Editor.
        /// </summary>
        public static string WalkEditorWithIcon {
            get {
                return ResourceManager.GetString("WalkEditorWithIcon", resourceCulture);
            }
        }
    }
}
