//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalkingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogWalkingApp.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog Walking Manager.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed:.
        /// </summary>
        public static string Breed {
            get {
                return ResourceManager.GetString("Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Details.
        /// </summary>
        public static string ClientDetails {
            get {
                return ResourceManager.GetString("ClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🙍 Client Details.
        /// </summary>
        public static string ClientDetailsWithIcon {
            get {
                return ResourceManager.GetString("ClientDetailsWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ColumnActions {
            get {
                return ResourceManager.GetString("ColumnActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string ColumnAge {
            get {
                return ResourceManager.GetString("ColumnAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed.
        /// </summary>
        public static string ColumnBreed {
            get {
                return ResourceManager.GetString("ColumnBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ColumnDate {
            get {
                return ResourceManager.GetString("ColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ColumnDuration {
            get {
                return ResourceManager.GetString("ColumnDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ColumnNotes {
            get {
                return ResourceManager.GetString("ColumnNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ColumnTime {
            get {
                return ResourceManager.GetString("ColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks.
        /// </summary>
        public static string ColumnWalks {
            get {
                return ResourceManager.GetString("ColumnWalks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks.
        /// </summary>
        public static string ColumnWalksCount {
            get {
                return ResourceManager.GetString("ColumnWalksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time:.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog Information.
        /// </summary>
        public static string DogInformation {
            get {
                return ResourceManager.GetString("DogInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogs.
        /// </summary>
        public static string Dogs {
            get {
                return ResourceManager.GetString("Dogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🐕 Dogs for Selected Client.
        /// </summary>
        public static string DogsForSelectedClient {
            get {
                return ResourceManager.GetString("DogsForSelectedClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (minutes):.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Credentials.
        /// </summary>
        public static string LoginCredentials {
            get {
                return ResourceManager.GetString("LoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Search.
        /// </summary>
        public static string SearchWithIcon {
            get {
                return ResourceManager.GetString("SearchWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk Details.
        /// </summary>
        public static string WalkDetails {
            get {
                return ResourceManager.GetString("WalkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk for: [Dog].
        /// </summary>
        public static string WalkFor {
            get {
                return ResourceManager.GetString("WalkFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walks.
        /// </summary>
        public static string Walks {
            get {
                return ResourceManager.GetString("Walks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚶 Walks for Selected Dog.
        /// </summary>
        public static string WalksForSelectedDog {
            get {
                return ResourceManager.GetString("WalksForSelectedDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years old.
        /// </summary>
        public static string YearsOld {
            get {
                return ResourceManager.GetString("YearsOld", resourceCulture);
            }
        }
    }
}
