//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalkingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UISizes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UISizes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogWalkingApp.Resources.UISizes", typeof(UISizes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string AgeInputLeft {
            get {
                return ResourceManager.GetString("AgeInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string BreedInputLeft {
            get {
                return ResourceManager.GetString("BreedInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ButtonCancelWidth {
            get {
                return ResourceManager.GetString("ButtonCancelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ButtonDeleteWidth {
            get {
                return ResourceManager.GetString("ButtonDeleteWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ButtonEditWidth {
            get {
                return ResourceManager.GetString("ButtonEditWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125.
        /// </summary>
        public static string ButtonLoginLeft {
            get {
                return ResourceManager.GetString("ButtonLoginLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ButtonLoginWidth {
            get {
                return ResourceManager.GetString("ButtonLoginWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ButtonNewWidth {
            get {
                return ResourceManager.GetString("ButtonNewWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75.
        /// </summary>
        public static string ButtonSaveWidth {
            get {
                return ResourceManager.GetString("ButtonSaveWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        public static string DateTimeInputLeft {
            get {
                return ResourceManager.GetString("DateTimeInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        public static string DurationInputLeft {
            get {
                return ResourceManager.GetString("DurationInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.
        /// </summary>
        public static string FormDogEditorWidth {
            get {
                return ResourceManager.GetString("FormDogEditorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 324.
        /// </summary>
        public static string FormLoginWidth {
            get {
                return ResourceManager.GetString("FormLoginWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 380.
        /// </summary>
        public static string FormWalkEditorWidth {
            get {
                return ResourceManager.GetString("FormWalkEditorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 295.
        /// </summary>
        public static string GroupLoginCredentials {
            get {
                return ResourceManager.GetString("GroupLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string LabelAgeWidth {
            get {
                return ResourceManager.GetString("LabelAgeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        public static string LabelBreedWidth {
            get {
                return ResourceManager.GetString("LabelBreedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66.
        /// </summary>
        public static string LabelDateTimeWidth {
            get {
                return ResourceManager.GetString("LabelDateTimeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56.
        /// </summary>
        public static string LabelDurationWidth {
            get {
                return ResourceManager.GetString("LabelDurationWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string LabelMinutesWidth {
            get {
                return ResourceManager.GetString("LabelMinutesWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string LabelNameWidth {
            get {
                return ResourceManager.GetString("LabelNameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.
        /// </summary>
        public static string LabelNotesWidth {
            get {
                return ResourceManager.GetString("LabelNotesWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        public static string LabelPasswordWidth {
            get {
                return ResourceManager.GetString("LabelPasswordWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44.
        /// </summary>
        public static string LabelPhoneWidth {
            get {
                return ResourceManager.GetString("LabelPhoneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 63.
        /// </summary>
        public static string LabelUsernameWidth {
            get {
                return ResourceManager.GetString("LabelUsernameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string NameInputLeft {
            get {
                return ResourceManager.GetString("NameInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string PasswordInputLeft {
            get {
                return ResourceManager.GetString("PasswordInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string PhoneInputLeft {
            get {
                return ResourceManager.GetString("PhoneInputLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string UsernameInputLeft {
            get {
                return ResourceManager.GetString("UsernameInputLeft", resourceCulture);
            }
        }
    }
}
