//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalkingApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DogWalkingApp.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client deleted successfully..
        /// </summary>
        public static string ClientDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ClientDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client saved successfully..
        /// </summary>
        public static string ClientSaved {
            get {
                return ResourceManager.GetString("ClientSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client saved successfully..
        /// </summary>
        public static string ClientSavedSuccessfully {
            get {
                return ResourceManager.GetString("ClientSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete client &apos;{0}&apos; and all associated dogs and walks?.
        /// </summary>
        public static string ConfirmDeleteClient {
            get {
                return ResourceManager.GetString("ConfirmDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete dog &apos;{0}&apos; and all associated walks?.
        /// </summary>
        public static string ConfirmDeleteDog {
            get {
                return ResourceManager.GetString("ConfirmDeleteDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the walk on {0}?.
        /// </summary>
        public static string ConfirmDeleteWalk {
            get {
                return ResourceManager.GetString("ConfirmDeleteWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the database. Please check your connection..
        /// </summary>
        public static string DatabaseConnectionError {
            get {
                return ResourceManager.GetString("DatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setup error: {0}.
        /// </summary>
        public static string DatabaseSetupError {
            get {
                return ResourceManager.GetString("DatabaseSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog added successfully..
        /// </summary>
        public static string DogAddedSuccessfully {
            get {
                return ResourceManager.GetString("DogAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog deleted successfully..
        /// </summary>
        public static string DogDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DogDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog saved successfully..
        /// </summary>
        public static string DogSaved {
            get {
                return ResourceManager.GetString("DogSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog updated successfully..
        /// </summary>
        public static string DogUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DogUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding dog: {0}.
        /// </summary>
        public static string ErrorAddingDog {
            get {
                return ResourceManager.GetString("ErrorAddingDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding walk: {0}.
        /// </summary>
        public static string ErrorAddingWalk {
            get {
                return ResourceManager.GetString("ErrorAddingWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting client: {0}.
        /// </summary>
        public static string ErrorDeletingClient {
            get {
                return ResourceManager.GetString("ErrorDeletingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting data. Please try again..
        /// </summary>
        public static string ErrorDeletingData {
            get {
                return ResourceManager.GetString("ErrorDeletingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting dog: {0}.
        /// </summary>
        public static string ErrorDeletingDog {
            get {
                return ResourceManager.GetString("ErrorDeletingDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting walk: {0}.
        /// </summary>
        public static string ErrorDeletingWalk {
            get {
                return ResourceManager.GetString("ErrorDeletingWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data. Please check your database connection..
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving client: {0}.
        /// </summary>
        public static string ErrorSavingClient {
            get {
                return ResourceManager.GetString("ErrorSavingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data. Please try again..
        /// </summary>
        public static string ErrorSavingData {
            get {
                return ResourceManager.GetString("ErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating dog: {0}.
        /// </summary>
        public static string ErrorUpdatingDog {
            get {
                return ResourceManager.GetString("ErrorUpdatingDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating walk: {0}.
        /// </summary>
        public static string ErrorUpdatingWalk {
            get {
                return ResourceManager.GetString("ErrorUpdatingWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error: {0}.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Client Selected.
        /// </summary>
        public static string NoClientSelected {
            get {
                return ResourceManager.GetString("NoClientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dog Selected.
        /// </summary>
        public static string NoDogSelected {
            get {
                return ResourceManager.GetString("NoDogSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for your search..
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both username and password..
        /// </summary>
        public static string PleaseEnterCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a client first to add a dog..
        /// </summary>
        public static string PleaseSelectClientForDog {
            get {
                return ResourceManager.GetString("PleaseSelectClientForDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a client to delete..
        /// </summary>
        public static string PleaseSelectClientToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectClientToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a client to edit..
        /// </summary>
        public static string PleaseSelectClientToEdit {
            get {
                return ResourceManager.GetString("PleaseSelectClientToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a dog first to add a walk..
        /// </summary>
        public static string PleaseSelectDogForWalk {
            get {
                return ResourceManager.GetString("PleaseSelectDogForWalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a dog to delete..
        /// </summary>
        public static string PleaseSelectDogToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectDogToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a dog to edit..
        /// </summary>
        public static string PleaseSelectDogToEdit {
            get {
                return ResourceManager.GetString("PleaseSelectDogToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a walk to delete..
        /// </summary>
        public static string PleaseSelectWalkToDelete {
            get {
                return ResourceManager.GetString("PleaseSelectWalkToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a walk to edit..
        /// </summary>
        public static string PleaseSelectWalkToEdit {
            get {
                return ResourceManager.GetString("PleaseSelectWalkToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search clients, dogs, or walks....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a client to view details..
        /// </summary>
        public static string SelectClient {
            get {
                return ResourceManager.GetString("SelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a dog to view walks..
        /// </summary>
        public static string SelectDog {
            get {
                return ResourceManager.GetString("SelectDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk added successfully..
        /// </summary>
        public static string WalkAddedSuccessfully {
            get {
                return ResourceManager.GetString("WalkAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk deleted successfully..
        /// </summary>
        public static string WalkDeletedSuccessfully {
            get {
                return ResourceManager.GetString("WalkDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk saved successfully..
        /// </summary>
        public static string WalkSaved {
            get {
                return ResourceManager.GetString("WalkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk updated successfully..
        /// </summary>
        public static string WalkUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("WalkUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
